# Site
title:              FAETEA designs
bio:                'The painting and wearables of Allison, known as Saphron.'
description:        "Moon is a minimal, one column jekyll theme for your blog."
reading_time:       false
words_per_minute:   200
logo:               'assets/img/faetea_roundlogo.png'
background:         'assets/img/rainbowBlurBG.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://faetea.com   #no trailing '/'
#url:                http://localhost:4000   #no trailing '/'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
email:              saphron@faetea.com
instagram:          faetea
etsy:               faetea
behance:            faetea
facebook:           faeteadesigns
#linkedin:          allisonsebastian
#twitter:           faetea
#github-url:        faetea
#pinterest:         saphronr
#googleplus:        saphronreyn
#keybase:           username
#lastfm:            username
#tumblr:            username
#flickr:            username
#soundcloud:        username
#dribbble:          username
#codepen:           username
#medium:            '@username'

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
